
import { Category, GlobalStore, Product } from './types';

export const DELIVERY_FEE = 20;

export const GLOBAL_STORES: GlobalStore[] = [
  { 
    id: '1', 
    name: 'Amazon', 
    url: 'https://www.amazon.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg', 
    description: { ar: 'متجر أمازون العالمي', en: 'Amazon Global Store', he: 'אמזון' } 
  },
  { 
    id: '2', 
    name: 'Shein', 
    url: 'https://www.shein.com', 
    logo: 'https://assets.stickpng.com/images/6011cbe72a08e9000490ab80.png', 
    description: { ar: 'أحدث صيحات الموضة العالمية', en: 'Trendy Fashion', he: 'אופנה' } 
  },
  { 
    id: '3', 
    name: 'AliExpress', 
    url: 'https://www.aliexpress.com', 
    logo: 'https://www.logo.wine/a/logo/AliExpress/AliExpress-Logo.wine.svg', 
    description: { ar: 'خيارك الأول للمنتجات المتنوعة', en: 'Diverse Products', he: 'מוצרים מגוונים' } 
  },
  { 
    id: '4', 
    name: 'eBay', 
    url: 'https://www.ebay.com', 
    logo: 'https://assets.stickpng.com/images/580b57fcd9996e24bc43c51d.png', 
    description: { ar: 'مزادات وشراء مباشر من العالم', en: 'Auctions & Buy It Now', he: 'מכירות פומביות' } 
  },
  { 
    id: '7', 
    name: 'Temu', 
    url: 'https://www.temu.com', 
    logo: 'https://images.seeklogo.com/logo-png/46/1/temu-logo-png_seeklogo-467490.png', 
    description: { ar: 'تسوق كأنك ملياردير - أسعار مذهلة', en: 'Competitive Prices', he: 'מחירים תחרותיים' } 
  },
  { 
    id: '8', 
    name: 'Wish', 
    url: 'https://www.wish.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Wish_Logo_2022.svg/512px-Wish_Logo_2022.svg.png', 
    description: { ar: 'اكتشف صفقات مذهلة وتوفير حقيقي', en: 'Amazing Deals', he: 'דילים מדהימים' } 
  },
];

export const CATEGORIES: Category[] = [
  { 
    id: 'clothes', 
    name: { ar: 'الملابس', en: 'Clothes', he: 'בגדים' }, 
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=1000&auto=format&fit=crop', 
    itemCount: 250,
    subCategories: [
      { id: 'men', name: { ar: 'رجالي', en: 'Men', he: 'גברים' } },
      { id: 'women', name: { ar: 'نسائي', en: 'Women', he: 'נשים' } },
      { id: 'kids', name: { ar: 'أطفال', en: 'Kids', he: 'ילדים' } },
    ]
  },
  { id: 'shoes', name: { ar: 'أحذية', en: 'Shoes', he: 'נעליים' }, image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop', itemCount: 45 },
  { id: 'accessories', name: { ar: 'إكسسوارات', en: 'Accessories', he: 'אביزرים' }, image: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980?q=80&w=1000&auto=format&fit=crop', itemCount: 32 },
  { id: 'home', name: { ar: 'منزل', en: 'Home', he: 'בית' }, image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop', itemCount: 18 },
];

export const MOCK_PRODUCTS: Product[] = [
  // Men (Big)
  {
    id: 'm1',
    name: { ar: 'طقم رجالي كاجوال', en: 'Men Casual Set', he: 'סט גברים יומיומי' },
    price: 350,
    category: 'clothes',
    subCategory: 'men',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'طقم رجالي صيفي مكون من قطعتين بجودة عالية.', en: 'Premium quality two-piece summer set for men.', he: 'סט קיץ לגברים' },
    brand: 'Urban Legend'
  },
  {
    id: 'm2',
    name: { ar: 'بليزر رجالي رسمي', en: 'Formal Men Blazer', he: 'בלייזר רשמי לגברים' },
    price: 520,
    oldPrice: 700,
    category: 'clothes',
    subCategory: 'men',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'بليزر أنيق للمناسبات الرسمية والعمل.', en: 'Elegant blazer for formal occasions and work.', he: 'בלייזר רשמי' },
    isSale: true,
    brand: 'Luxury Fit'
  },
  // Women (Big)
  {
    id: 'w1',
    name: { ar: 'فستان مخملي سهرة', en: 'Velvet Evening Dress', he: 'שמלת ערב קטיפה' },
    price: 850,
    category: 'clothes',
    subCategory: 'women',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'فستان سهرة فاخر من المخمل الناعم.', en: 'Luxury evening dress made of soft velvet.', he: 'שמלת ערב' },
    brand: 'Rose Boutique'
  },
  // Kids (Small - Boys)
  {
    id: 'k1',
    name: { ar: 'بدلة أطفال - ولادي', en: 'Boys Formal Suit', he: 'חליפת ילדים לבנים' },
    price: 210,
    category: 'clothes',
    subCategory: 'kids',
    targetAge: 'child',
    image: 'https://images.unsplash.com/photo-1519234110450-149021d46982?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'بدلة رسمية للأطفال الصغار تناسب الأفراح.', en: 'Formal suit for little boys, perfect for weddings.', he: 'חליפה לילדים' },
    isNew: true,
    brand: 'Little Gent'
  },
  // Row 2 Items (New Added)
  {
    id: 'acc1',
    name: { ar: 'ساعة يد كلاسيكية', en: 'Classic Wristwatch', he: 'שעון יד קלאסי' },
    price: 450,
    oldPrice: 600,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'ساعة جلدية فاخرة تناسب جميع الأذواق.', en: 'Luxury leather watch for all styles.', he: 'שעון יוקרתי' },
    isSale: true,
    brand: 'TimeMaster'
  },
  {
    id: 'w2',
    name: { ar: 'حقيبة يد عصرية', en: 'Modern Handbag', he: 'תיק יד מודרני' },
    price: 320,
    category: 'accessories',
    subCategory: 'women',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'حقيبة يد جلدية بتصميم فريد وأنيق.', en: 'Unique and elegant leather handbag.', he: 'תיק יד מעור' },
    isNew: true,
    brand: 'Elle'
  },
  {
    id: 'k2',
    name: { ar: 'فستان بناتي مزهر', en: 'Girls Floral Dress', he: 'שמלת פרחים לבנות' },
    price: 180,
    category: 'clothes',
    subCategory: 'kids',
    targetAge: 'child',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'فستان صيفي ملون للأطفال الصغار.', en: 'Colorful summer dress for kids.', he: 'שמלת קיץ לילדים' },
    brand: 'Princess Cut'
  },
  {
    id: 'm3',
    name: { ar: 'قميص أكسفورد أبيض', en: 'White Oxford Shirt', he: 'חולצת אוקספורד לבנה' },
    price: 190,
    oldPrice: 250,
    category: 'clothes',
    subCategory: 'men',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c7176c8?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'قميص قطني ناعم وعملي للإطلالات اليومية.', en: 'Soft and practical cotton shirt for daily looks.', he: 'חולצה יומיומית' },
    brand: 'Cotton Pure'
  }
];

export const TRANSLATIONS = {
  ar: {
    home: 'الرئيسية',
    localShopping: 'تسوق محلي',
    globalShopping: 'تسوق عالمي',
    about: 'من نحن',
    contact: 'اتصل بنا',
    searchPlaceholder: 'ابحث عن المنتجات...',
    bestsellers: 'الأكثر مبيعاً هذا الأسبوع',
    browseCategories: 'تصفح حسب الأقسام',
    browseCategoriesDesc: 'اكتشف مجموعتنا الواسعة من المنتجات المحلية المميزة',
    specialOffers: 'عروض خاصة',
    viewAll: 'عرض الكل',
    addToCart: 'أضف للسلة',
    visitStore: 'زيارة المتجر',
    price: 'السعر',
    currency: 'ش.ج',
    orderForm: 'نموذج الطلب',
    name: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    city: 'المدينة',
    submitOrder: 'تأكيد الطلب',
    deliveryFee: 'رسوم التوصيل',
    total: 'المجموع',
    freeShipping: 'شحن مجاني للطلبات فوق 500 ش.ج',
    footerDesc: 'تجربة تسوق استثنائية تجمع بين المحلية والعالمية.',
    rights: 'جميع الحقوق محفوظة © 2024 LAVIVAA',
    subscribe: 'اشترك في النشرة البريدية',
    subscribeDesc: 'احصل على آخر العروض والأخبار',
    heroTitle: 'تصميم رائع يجمع بين الوظائف',
    heroSub: 'استمتع بتجربة تسوق فريدة مع أفضل المتاجر المحلية والعالمية.',
    shopNow: 'تسوق الآن',
    explore: 'اكتشف المزيد',
    filter: 'فلترة',
    newArrivals: 'وصل حديثاً',
    sale: 'تخفيضات',
    close: 'إغلاق',
    cart: 'السلة',
    emptyCart: 'السلة فارغة',
    checkout: 'إتمام الطلب',
    successOrder: 'تم استلام طلبك بنجاح!',
    sku: 'رمز المنتج',
    category: 'التصنيف',
    brand: 'العلامة التجارية',
    description: 'الوصف',
    additionalInfo: 'معلومات إضافية',
    reviews: 'المراجعات',
    relatedProducts: 'منتجات ذات صلة',
    wishlist: 'قائمة الرغبات',
    compare: 'مقارنة',
    sizeGuide: 'دليل المقاسات',
    share: 'مشاركة',
    shop: 'المتجر',
    billingDetails: 'تفاصيل الفاتورة',
    orderSummary: 'ملخص الطلب',
    placeOrder: 'تأكيد الطلب',
    cartEmpty: 'سلة التسوق فارغة',
    continueShopping: 'متابعة التسوق',
    whyShopGlobal: 'لماذا تتسوق عالمياً عبر LAVIVAA؟',
    feature1Title: 'روابط موثوقة',
    feature1Desc: 'ادخل إلى المتاجر الرسمية بأمان من خلال روابطنا التابعة والموثوقة.',
    feature2Title: 'أفضل العروض',
    feature2Desc: 'نحن نجمع لك أفضل الصفقات العالمية في مكان واحد من أجلك.',
    feature3Title: 'سهولة التنقل',
    feature3Desc: 'اعثر على ما تحتاجه بالضبط من كبار تجار التجزئة العالميين بسرعة.',
    men: 'رجالي',
    women: 'نسائي',
    kids: 'أطفال',
    adult: 'كبار',
    child: 'صغار',
    gender: 'الجنس',
    ageGroup: 'الفئة العمرية',
  },
  en: {
    home: 'Home',
    localShopping: 'Local Shopping',
    globalShopping: 'Global Shopping',
    about: 'About Us',
    contact: 'Contact',
    searchPlaceholder: 'Search products...',
    bestsellers: 'Bestsellers of the week',
    browseCategories: 'Browse by Categories',
    browseCategoriesDesc: 'Discover our wide range of premium local products',
    specialOffers: 'Special Offers',
    viewAll: 'View All',
    addToCart: 'Add to cart',
    visitStore: 'Visit Store',
    price: 'Price',
    currency: 'NIS',
    orderForm: 'Order Form',
    name: 'Full Name',
    phone: 'Phone Number',
    address: 'Address',
    city: 'City',
    submitOrder: 'Confirm Order',
    deliveryFee: 'Delivery Fee',
    total: 'Total',
    freeShipping: 'Free shipping on orders over 500 NIS',
    footerDesc: 'An exceptional shopping experience combining local and global.',
    rights: 'All rights reserved © 2024 LAVIVAA',
    subscribe: 'Subscribe to Newsletter',
    subscribeDesc: 'Get the latest offers and news',
    heroTitle: 'Exquisite design combined with functionalities',
    heroSub: 'Enjoy a unique shopping experience with best local and global stores.',
    shopNow: 'Shop Now',
    explore: 'Explore Now',
    filter: 'Filter',
    newArrivals: 'New Arrivals',
    sale: 'Sale',
    close: 'Close',
    cart: 'Cart',
    emptyCart: 'Your cart is empty',
    checkout: 'Checkout',
    successOrder: 'Order received successfully!',
    sku: 'SKU',
    category: 'Category',
    brand: 'Brand',
    description: 'Description',
    additionalInfo: 'Additional Information',
    reviews: 'Reviews',
    relatedProducts: 'Related products',
    wishlist: 'Wishlist',
    compare: 'Compare',
    sizeGuide: 'Size Guide',
    share: 'Share',
    shop: 'Shop',
    billingDetails: 'Billing Details',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    cartEmpty: 'Your cart is empty',
    continueShopping: 'Continue Shopping',
    whyShopGlobal: 'Why Shop Global via LAVIVAA?',
    feature1Title: 'Verified Links',
    feature1Desc: 'Access official stores safely through our verified affiliate links.',
    feature2Title: 'Best Deals',
    feature2Desc: 'We aggregate the best global deals in one place for you.',
    feature3Title: 'Easy Navigation',
    feature3Desc: 'Find exactly what you need from top global retailers quickly.',
    men: 'Men',
    women: 'Women',
    kids: 'Kids',
    adult: 'Adults',
    child: 'Children',
    gender: 'Gender',
    ageGroup: 'Age Group',
  },
  he: {
    home: 'בית',
    localShopping: 'קניות מקומיות',
    globalShopping: 'קניות גלובליות',
    about: 'עלינו',
    contact: 'צור קשר',
    searchPlaceholder: 'חפש מוצרים...',
    bestsellers: 'הנמכרים ביותר השבוע',
    browseCategories: 'דפדף לפי קטגוריות',
    browseCategoriesDesc: 'גלה את המגוון הרחב של מוצרים מקומיים איכותיים',
    specialOffers: 'מבצעים מיוחדים',
    viewAll: 'הצג הכל',
    addToCart: 'הוסף לסל',
    visitStore: 'בקר בחנות',
    price: 'מחיר',
    currency: '₪',
    orderForm: 'טופס הזמנה',
    name: 'שם מלא',
    phone: 'מספר טלפון',
    address: 'כתובת',
    city: 'עיר',
    submitOrder: 'אשר הזמנה',
    deliveryFee: 'דמי משלוח',
    total: 'סה"כ',
    freeShipping: 'משלוח חינם בהזמנות מעל 500 ₪',
    footerDesc: 'חווית קניות יוצאת דופן המשלבת מקומי וגלובלי.',
    rights: 'כל הזכויות שמורות © 2024 LAVIVAA',
    subscribe: 'הירשם לניוזלטר',
    subscribeDesc: 'קבל את המבצעים והחדשות האחרונים',
    heroTitle: 'עיצוב מעולה בשילוב פונקציונליות',
    heroSub: 'תיהנו מחווית קניות ייחודית עם מיטב החנויות המקומיות והעולמיות.',
    shopNow: 'קנה עכשיו',
    explore: 'גלה עוד',
    filter: 'סינון',
    newArrivals: 'חדש',
    sale: 'מבצע',
    close: 'סגור',
    cart: 'עגלה',
    emptyCart: 'העגלה ריקה',
    checkout: 'לקופה',
    successOrder: 'ההזמנה התקבלה בהצלחה!',
    sku: 'מק"ט',
    category: 'קטגוריה',
    brand: 'מותג',
    description: 'תיאור',
    additionalInfo: 'מידע נוסף',
    reviews: 'ביקורות',
    relatedProducts: 'מוצרים קשורים',
    wishlist: 'רשימת משאלות',
    compare: 'השוואה',
    sizeGuide: 'מדריך מידות',
    share: 'שתף',
    shop: 'חנות',
    billingDetails: 'פרטי חיוב',
    orderSummary: 'סיכום הזמנה',
    placeOrder: 'בצע הזמנה',
    cartEmpty: 'עגלת הקניות ריקה',
    continueShopping: 'המשך בקניות',
    whyShopGlobal: 'למה לקנות גלובלי דרך LAVIVAA?',
    feature1Title: 'קישורים מאומתים',
    feature1Desc: 'גישה לחנויות רשמיות בבטחה דרך קישורי השותפים המאומתים שלנו.',
    feature2Title: 'הדילים הטובים ביותר',
    feature2Desc: 'אנחנו אוספים את המבצעים הגלובליים הטובים ביותר במקום אחד עבורכם.',
    feature3Title: 'ניווט קל',
    feature3Desc: 'מצא בדיוק את מה שאתה צריך מהקמעונאים הגלובליים המובילים במהירות.',
    men: 'גברים',
    women: 'נשים',
    kids: 'ילדים',
    adult: 'מבוגרים',
    child: 'ילדים',
    gender: 'מגדר',
    ageGroup: 'קבוצת גיל',
  }
};
