
import { Category, GlobalStore, Product } from './types';

export const DELIVERY_FEE = 20;

export const GLOBAL_STORES: GlobalStore[] = [
  { 
    id: '1', 
    name: 'Amazon', 
    url: 'https://www.amazon.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg', 
    description: { ar: 'متجر أمازون العالمي', en: 'Amazon Global Store' } 
  },
  { 
    id: '2', 
    name: 'Shein', 
    url: 'https://www.shein.com', 
    logo: 'https://assets.stickpng.com/images/6011cbe72a08e9000490ab80.png', 
    description: { ar: 'أحدث صيحات الموضة العالمية', en: 'Latest Global Fashion Trends' } 
  },
  { 
    id: '3', 
    name: 'AliExpress', 
    url: 'https://www.aliexpress.com', 
    logo: 'https://www.logo.wine/a/logo/AliExpress/AliExpress-Logo.wine.svg', 
    description: { ar: 'خيارك الأول للمنتجات المتنوعة', en: 'Your First Choice for Variety' } 
  },
  { 
    id: '4', 
    name: 'eBay', 
    url: 'https://www.ebay.com', 
    logo: 'https://assets.stickpng.com/images/580b57fcd9996e24bc43c51d.png', 
    description: { ar: 'مزادات وشراء مباشر من العالم', en: 'Auctions & Global Direct Buy' } 
  },
  { 
    id: '7', 
    name: 'Temu', 
    url: 'https://www.temu.com', 
    logo: 'https://images.seeklogo.com/logo-png/46/1/temu-logo-png_seeklogo-467490.png', 
    description: { ar: 'تسوق كأنك ملياردير - أسعار مذهلة', en: 'Shop Like a Billionaire - Amazing Prices' } 
  },
  { 
    id: '8', 
    name: 'Wish', 
    url: 'https://www.wish.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Wish_Logo_2022.svg/512px-Wish_Logo_2022.svg.png', 
    description: { ar: 'اكتشف صفقات مذهلة وتوفير حقيقي', en: 'Discover Amazing Deals & Savings' } 
  },
];

export const CATEGORIES: Category[] = [
  { 
    id: 'clothes', 
    name: { ar: 'الملابس', en: 'Apparel' }, 
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=1000&auto=format&fit=crop', 
    itemCount: 250,
    subCategories: [
      { id: 'men', name: { ar: 'رجالي', en: 'Men' } },
      { id: 'women', name: { ar: 'نسائي', en: 'Women' } },
      { id: 'kids', name: { ar: 'أطفال', en: 'Kids' } },
    ]
  },
  { id: 'shoes', name: { ar: 'أحذية', en: 'Footwear' }, image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop', itemCount: 45 },
  { id: 'accessories', name: { ar: 'إكسسوارات', en: 'Accessories' }, image: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980?q=80&w=1000&auto=format&fit=crop', itemCount: 32 },
  { id: 'home', name: { ar: 'منزل', en: 'Home Decor' }, image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop', itemCount: 18 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'm1',
    name: { ar: 'طقم رجالي كاجوال', en: 'Men Casual Set' },
    price: 350,
    category: 'clothes',
    subCategory: 'men',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'طقم رجالي صيفي مكون من قطعتين بجودة عالية.', en: 'High-quality two-piece summer set for men.' },
    brand: 'Urban Legend'
  },
  {
    id: 'm2',
    name: { ar: 'بليزر رجالي رسمي', en: 'Formal Men Blazer' },
    price: 520,
    oldPrice: 700,
    category: 'clothes',
    subCategory: 'men',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'بليزر أنيق للمناسبات الرسمية والعمل.', en: 'Elegant blazer for formal occasions and business.' },
    isSale: true,
    brand: 'Luxury Fit'
  },
  {
    id: 'w1',
    name: { ar: 'فستان مخملي سهرة', en: 'Velvet Evening Dress' },
    price: 850,
    category: 'clothes',
    subCategory: 'women',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'فستان سهرة فاخر من المخمل الناعم.', en: 'Luxury evening dress made of soft premium velvet.' },
    brand: 'Rose Boutique'
  },
  {
    id: 'k1',
    name: { ar: 'بدلة أطفال - ولادي', en: 'Boys Formal Suit' },
    price: 210,
    category: 'clothes',
    subCategory: 'kids',
    targetAge: 'child',
    image: 'https://images.unsplash.com/photo-1519234110450-149021d46982?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'بدلة رسمية للأطفال الصغار تناسب الأفراح.', en: 'Formal suit for young boys, perfect for celebrations.' },
    isNew: true,
    brand: 'Little Gent'
  },
  {
    id: 'acc1',
    name: { ar: 'ساعة يد كلاسيكية', en: 'Classic Wristwatch' },
    price: 450,
    oldPrice: 600,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'ساعة جلدية فاخرة تناسب جميع الأذواق.', en: 'Luxury leather watch suitable for all styles.' },
    isSale: true,
    brand: 'TimeMaster'
  },
  {
    id: 'w2',
    name: { ar: 'حقيبة يد عصرية', en: 'Modern Handbag' },
    price: 320,
    category: 'accessories',
    subCategory: 'women',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'حقيبة يد جلدية بتصميم فريد وأنيق.', en: 'Leather handbag with a unique and elegant design.' },
    isNew: true,
    brand: 'Elle'
  },
  {
    id: 'k2',
    name: { ar: 'فستان بناتي مزهر', en: 'Girls Floral Dress' },
    price: 180,
    category: 'clothes',
    subCategory: 'kids',
    targetAge: 'child',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'فستان صيفي ملون للأطفال الصغار.', en: 'Colorful summer dress for young children.' },
    brand: 'Princess Cut'
  },
  {
    id: 'm3',
    name: { ar: 'قميص أكسفورد أبيض', en: 'White Oxford Shirt' },
    price: 190,
    oldPrice: 250,
    category: 'clothes',
    subCategory: 'men',
    targetAge: 'adult',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c7176c8?q=80&w=800&auto=format&fit=crop',
    isLocal: true,
    description: { ar: 'قميص قطني ناعم وعملي للإطلالات اليومية.', en: 'Soft and practical cotton shirt for daily wear.' },
    brand: 'Cotton Pure'
  }
];

export const TRANSLATIONS = {
  ar: {
    home: 'الرئيسية',
    localShopping: 'تسوق محلي',
    globalShopping: 'تسوق عالمي',
    about: 'من نحن',
    contact: 'اتصل بنا',
    searchPlaceholder: 'ابحث عن المنتجات...',
    bestsellers: 'الأكثر مبيعاً هذا الأسبوع',
    browseCategories: 'تصفح حسب الأقسام',
    browseCategoriesDesc: 'اكتشف مجموعتنا الواسعة من المنتجات المحلية المميزة',
    specialOffers: 'عروض خاصة',
    viewAll: 'عرض الكل',
    addToCart: 'أضف للسلة',
    visitStore: 'زيارة المتجر',
    price: 'السعر',
    currency: 'ش.ج',
    orderForm: 'نموذج الطلب',
    name: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    city: 'المدينة',
    submitOrder: 'تأكيد الطلب',
    deliveryFee: 'رسوم التوصيل',
    total: 'المجموع',
    freeShipping: 'شحن مجاني للطلبات فوق 500 ش.ج',
    footerDesc: 'تجربة تسوق استثنائية تجمع بين المحلية والعالمية.',
    rights: 'جميع الحقوق محفوظة © 2024 LAVIVAA',
    subscribe: 'اشترك في النشرة البريدية',
    subscribeDesc: 'احصل على آخر العروض والأخبار',
    welcomeLuxury: 'مرحباً بك في عالم الفخامة',
    heroTitlePart1: 'تسوق ',
    heroTitleLocal: 'المحلي',
    heroTitlePart2: ' بلمسة ',
    heroTitleGlobal: 'عالمية',
    heroSub: 'اكتشف مجموعتنا المختارة بعناية من أفضل المتاجر المحلية، وانطلق لاستكشاف العروض العالمية المذهلة.',
    shopNow: 'تسوق الآن',
    explore: 'اكتشف المزيد',
    filter: 'فلترة',
    newArrivals: 'وصل حديثاً',
    sale: 'تخفيضات',
    close: 'إغلاق',
    cart: 'السلة',
    emptyCart: 'السلة فارغة',
    checkout: 'إتمام الطلب',
    successOrder: 'تم استلام طلبك بنجاح!',
    sku: 'رمز المنتج',
    category: 'التصنيف',
    brand: 'العلامة التجارية',
    description: 'الوصف',
    additionalInfo: 'معلومات إضافية',
    reviews: 'المراجعات',
    relatedProducts: 'منتجات ذات صلة',
    wishlist: 'قائمة الرغبات',
    compare: 'مقارنة',
    sizeGuide: 'دليل المقاسات',
    share: 'مشاركة',
    shop: 'المتجر',
    billingDetails: 'تفاصيل الفاتورة',
    orderSummary: 'ملخص الطلب',
    placeOrder: 'تأكيد الطلب',
    cartEmpty: 'سلة التسوق فارغة',
    continueShopping: 'متابعة التسوق',
    whyShopGlobal: 'لماذا تتسوق عالمياً عبر LAVIVAA؟',
    feature1Title: 'روابط موثوقة',
    feature1Desc: 'ادخل إلى المتاجر الرسمية بأمان من خلال روابطنا التابعة والموثوقة.',
    feature2Title: 'أفضل العروض',
    feature2Desc: 'نحن نجمع لك أفضل الصفقات العالمية في مكان واحد من أجلك.',
    feature3Title: 'سهولة التنقل',
    feature3Desc: 'اعثر على ما تحتاجه بالضبط من كبار تجار التجزئة العالميين بسرعة.',
    men: 'رجالي',
    women: 'نسائي',
    kids: 'أطفال',
    adult: 'كبار',
    child: 'صغار',
    gender: 'الجنس',
    ageGroup: 'الفئة العمرية',
    support247: 'دعم فني',
    supportDesc: '24/7 متاح دائماً',
    authentic100: 'أصالة المنتجات',
    authenticDesc: 'منتجات أصلية 100%',
    globalStoresCount: 'متجر عالمي',
    bigSale: 'تخفيضات كبرى',
    bigSaleDesc: 'خصم يصل إلى 50% على قطع مختارة من المتاجر المحلية.',
    categoriesSub: 'كل ما تحتاجه في مكان واحد، مقسم بعناية لراحتك.',
    bestsellersSub: 'القطع الأكثر طلباً وتميزاً لهذا الأسبوع في متجرنا المحلي.',
    whatMakesUsSpecial: 'ما يميزنا في',
    fastShipping: 'شحن سريع',
    fastShippingDesc: 'توصيل سريع وآمن لجميع المناطق خلال وقت قياسي.',
    securePayment: 'دفع آمن',
    securePaymentDesc: 'خيارات دفع متعددة مع حماية كاملة لبياناتك.',
    easyReturns: 'استرجاع سهل',
    easyReturnsDesc: 'إمكانية الإرجاع والاستبدال بسهولة ومرونة.',
    luxuryPackaging: 'تغليف فاخر',
    luxuryPackagingDesc: 'تغليف أنيق وجذاب مثالي للهدايا والمناسبات.',
    experienceTitle: 'نسعى لتقديم تجربة تسوق تفوق التوقعات',
    experienceDesc: 'منذ بدايتنا، هدفنا هو جسر الهوة بين التسوق المحلي بجودته العالية والتسوق العالمي بتنوعه الهائل.',
    fullSecurity: 'أمان تام',
    fullSecurityDesc: 'عمليات دفع مشفرة وآمنة بنسبة 100%.',
    superSpeed: 'سرعة فائقة',
    superSpeedDesc: 'توصيل محلي في زمن قياسي وروابط عالمية مباشرة.',
    happyCustomers: 'عميل سعيد يثق بنا دائماً.',
    productsFound: 'منتجات تم العثور عليها',
    applyFilter: 'تطبيق الفلترة',
    noProductsFound: 'لا توجد منتجات مطابقة',
    noProductsDesc: 'جرب تغيير إعدادات الفلترة أو مسح الكل للوصول إلى خيارات أكثر.',
    clearFilters: 'مسح جميع الفلاتر',
    location: 'الموقع',
    palestine: 'فلسطين',
    jerusalem: 'القدس',
    email: 'البريد الإلكتروني',
    whatsapp: 'واتساب',
    globalBadge1: 'تسوق عالمي',
    globalBadge2: 'عروض حصرية',
    globalBadge3: 'وصل حديثاً',
    globalSlide1Title: 'وجهتك نحو العالم',
    globalSlide1Sub: 'نتيح لك الوصول إلى أشهر المتاجر العالمية بضغطة زر واحدة.',
    globalSlide2Title: 'أحدث صيحات الموضة',
    globalSlide2Sub: 'اكتشف تشكيلات حصرية من برانداتك العالمية المفضلة بأسعار تنافسية.',
    globalSlide3Title: 'تكنولوجيا بلا حدود',
    globalSlide3Sub: 'أحدث الأدوات والتقنيات الذكية تصلك من متاجر التجزئة الكبرى.',
  },
  en: {
    home: 'Home',
    localShopping: 'Local Shopping',
    globalShopping: 'Global Shopping',
    about: 'About Us',
    contact: 'Contact',
    searchPlaceholder: 'Search for products...',
    bestsellers: 'Weekly Bestsellers',
    browseCategories: 'Browse Categories',
    browseCategoriesDesc: 'Discover our wide range of premium local products',
    specialOffers: 'Special Offers',
    viewAll: 'View All',
    addToCart: 'Add to Cart',
    visitStore: 'Visit Store',
    price: 'Price',
    currency: 'NIS',
    orderForm: 'Order Form',
    name: 'Full Name',
    phone: 'Phone Number',
    address: 'Address',
    city: 'City',
    submitOrder: 'Confirm Order',
    deliveryFee: 'Delivery Fee',
    total: 'Total',
    freeShipping: 'Free shipping on orders over 500 NIS',
    footerDesc: 'An exceptional shopping experience combining local quality and global variety.',
    rights: 'All Rights Reserved © 2024 LAVIVAA',
    subscribe: 'Subscribe to Newsletter',
    subscribeDesc: 'Get the latest offers and news directly',
    welcomeLuxury: 'Welcome to the World of Luxury',
    heroTitlePart1: 'Shop ',
    heroTitleLocal: 'Local',
    heroTitlePart2: ' with a ',
    heroTitleGlobal: 'Global Touch',
    heroSub: 'Explore our carefully curated collection from top local stores, and discover amazing global deals from across the world.',
    shopNow: 'Shop Now',
    explore: 'Explore More',
    filter: 'Filter',
    newArrivals: 'New Arrivals',
    sale: 'On Sale',
    close: 'Close',
    cart: 'Shopping Cart',
    emptyCart: 'Your cart is empty',
    checkout: 'Checkout',
    successOrder: 'Your order has been placed successfully!',
    sku: 'SKU',
    category: 'Category',
    brand: 'Brand',
    description: 'Description',
    additionalInfo: 'Additional Info',
    reviews: 'Reviews',
    relatedProducts: 'Related Products',
    wishlist: 'Wishlist',
    compare: 'Compare',
    sizeGuide: 'Size Guide',
    share: 'Share',
    shop: 'Shop',
    billingDetails: 'Billing Details',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    cartEmpty: 'Your shopping cart is empty',
    continueShopping: 'Continue Shopping',
    whyShopGlobal: 'Why Shop Globally via LAVIVAA?',
    feature1Title: 'Trusted Connections',
    feature1Desc: 'Access official stores safely through our verified affiliate links.',
    feature2Title: 'Best Global Deals',
    feature2Desc: 'We aggregate the finest international deals in one convenient place.',
    feature3Title: 'Easy Navigation',
    feature3Desc: 'Find exactly what you need from major global retailers quickly and easily.',
    men: 'Men',
    women: 'Women',
    kids: 'Kids',
    adult: 'Adults',
    child: 'Children',
    gender: 'Gender',
    ageGroup: 'Age Group',
    support247: '24/7 Support',
    supportDesc: 'Always Available',
    authentic100: '100% Authentic',
    authenticDesc: 'Guaranteed Products',
    globalStoresCount: 'Global Stores',
    bigSale: 'Big Sales',
    bigSaleDesc: 'Up to 50% off on selected items from our local partners.',
    categoriesSub: 'Everything you need in one place, carefully organized for your convenience.',
    bestsellersSub: 'The most requested and distinguished pieces of the week in our local store.',
    whatMakesUsSpecial: 'What Makes Us Special at',
    fastShipping: 'Fast Shipping',
    fastShippingDesc: 'Quick and secure delivery to all regions in record time.',
    securePayment: 'Secure Payment',
    securePaymentDesc: 'Multiple payment options with full protection for your data.',
    easyReturns: 'Easy Returns',
    easyReturnsDesc: 'Flexible return and exchange policy for your peace of mind.',
    luxuryPackaging: 'Luxury Packaging',
    luxuryPackagingDesc: 'Elegant and attractive packaging, perfect for gifts and occasions.',
    experienceTitle: 'Providing an Experience Beyond Expectations',
    experienceDesc: 'Since our beginning, our goal has been to bridge the gap between high-quality local shopping and vast global variety.',
    fullSecurity: 'Full Security',
    fullSecurityDesc: '100% encrypted and secure transactions.',
    superSpeed: 'Super Speed',
    superSpeedDesc: 'Record-time local delivery and direct global links.',
    happyCustomers: 'Happy customers who always trust us.',
    productsFound: 'products found',
    applyFilter: 'Apply Filters',
    noProductsFound: 'No matching products found',
    noProductsDesc: 'Try changing the filter settings or clear all to see more options.',
    clearFilters: 'Clear All Filters',
    location: 'Location',
    palestine: 'Palestine',
    jerusalem: 'Jerusalem',
    email: 'Email',
    whatsapp: 'WhatsApp',
    globalBadge1: 'Global Shopping',
    globalBadge2: 'Exclusive Offers',
    globalBadge3: 'New Arrivals',
    globalSlide1Title: 'Your Window to the World',
    globalSlide1Sub: 'Access the world\'s most famous stores with a single click.',
    globalSlide2Title: 'Latest Fashion Trends',
    globalSlide2Sub: 'Discover exclusive collections from your favorite global brands at competitive prices.',
    globalSlide3Title: 'Technology Without Limits',
    globalSlide3Sub: 'The latest smart tools and tech delivered to you from major global retailers.',
  }
};
